server:
  port: 8082

spring:
  application:
    name: second-service

eureka:
  #  instance:
  #    instance-id: ${spring.cloud.client.hostname}:${spring.application.instanceid}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka